---
title: "R Notebook"
output: html_notebook
---

# import libraries 
```{r}
#create a function to ensure the libraries are imported
EnsurePackage <- function(x){
  x <- as.character(x)
    if (!require(x,character.only = TRUE)){
      install.packages(pkgs=x, repos = "http://cran.us.r-project.org")
      require(x, character.only = TRUE)
    }
  }
# usage example, to load the necessary library for further processing...
EnsurePackage("RWeka")
EnsurePackage("ggplot2")
cat("All Pacakges loaded")
```

```{r}
#read from files
  trainset <- read.csv("/Users/sathishrajendiran/Documents/R/Titanic/titanic-train.csv")
  testset  <- read.csv("/Users/sathishrajendiran/Documents/R/Titanic/titanic-test.csv")

  # View(trainset)
  # View(testset)
  
  str(trainset)
  cat("\n")
  str(testset)
  
  cat("\n summary")
  summary(trainset)
  cat("\n")
  summary(testset)
```


```{r}
#Preprocessing
  NN <- make_Weka_filter("weka/filters/unsupervised/attribute/NumericToNominal")
  
  trainset <- NN(data=trainset, control= Weka_control(R="1-3"), na.action = NULL)
  testset <- NN(data=testset, control= Weka_control(R="1,3"), na.action = NULL)
  
  str(trainset)
  cat("\n")
  str(testset)
  
  cat("\n summary")
  summary(trainset)
  cat("\n")
  summary(testset)
```
```{r}
#Missing Values

  MS <- make_Weka_filter("weka/filters/unsupervised/attribute/ReplaceMissingValues") 
  trainset <-MS(data=trainset, na.action = NULL)
  testset <-MS(data=testset, na.action = NULL)

  cat("\n summary")
  summary(trainset)
  cat("\n")
  summary(testset)
  
  cat("\n Structure")
  str(trainset)
  cat("\n")
  str(testset)

```
```{r}
# APPLY J48 Algorithm
  m=J48(Survived~., data = trainset)
  m=J48(Survived~., data = trainset, control=Weka_control(U=FALSE, M=2,C=0.5))
  # WOW("J48")
```
```{r}
  #evaluate the model
  e <- evaluate_Weka_classifier(m, numFolds = 10, seed = 1, class = TRUE)
  e
```
```{r}
#prediction  
  pred=predict (m, newdata = testset, type = c("class"))
  pred
  summary(pred)
  
  write.csv(pred, file="/Users/sathishrajendiran/Documents/R/Titanic/titanic-pred.csv")
  
```


```{r}
 #model 1: no feature engineering

  m=J48(Survived~., data = trainset, control=Weka_control(U=FALSE, M=2, C=0.5))
  e <- evaluate_Weka_classifier(m, numFolds = 10, seed = 1, class = TRUE)
  pred=predict (m, newdata = testset, type = c("class"))
  myids=c("PassengerId")
  id_col=testset[myids]
  newpred=cbind(id_col, pred)
  colnames(newpred)=c("Passengerid", "Survived")
  write.csv(newpred, file="/Users/sathishrajendiran/Documents/R/Titanic/titanic_pred1.csv", row.names=FALSE)
  summary(newpred)
  
```
```{r}
# model 2: some feature selection

  myVars=c("Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Survived")
  newtrain=trainset[myVars]
  newtest=testset[myVars]
  m=J48(Survived~., data = newtrain)
  m=J48(Survived~., data = newtrain, control=Weka_control(U=FALSE, M=2, C=0.5))
  e=evaluate_Weka_classifier(m, seed=1, numFolds=10)
  pred=predict (m, newdata = newtest, type = c("class"))
  myids=c("PassengerId")
  id_col=testset[myids]
  newpred=cbind(id_col, pred)
  colnames(newpred)=c("Passengerid", "Survived")
  View(newpred)
  write.csv(newpred, file="/Users/sathishrajendiran/Documents/R/Titanic/titanic_pred2.csv", row.names=FALSE)
  
  summary(newpred)
```

